#!/bin/bash

. /etc/jelastic/environment

cd ${OPENSHIFT_JETTY8_DIR}/versions/${Version}/

if [ -e /opt/repo/versions/${Version}/bin/variablesparser.sh ]; then
    . /opt/repo/versions/${Version}/bin/variablesparser.sh
fi

jetty_pid=`ps aux|grep java|grep jetty|grep -v grep|awk '{print $2}'`;

JETTY_NODE=$(echo $JETTY_HOST | cut -f 1 -d".")

[ -n "$jetty_pid" ] && echo "Server already started" && exit 0;

CMD="java -jar $JAVA_OPTS start.jar -Djetty.host=$OPENSHIFT_JETTY8_APP_HOST -Djetty.port=$OPENSHIFT_JETTY8_APP_PORT -Dnode.name=$JETTY_NODE -Djava.net.preferIPv4Stack=true"

nohup $CMD >> $OPENSHIFT_JETTY8_LOG_DIR/server.log 2>&1 &

echo $! > jetty.pid && echo "Jetty8 started successfully"
